# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b59363d688a7408bcffd9b62e341e671c78460556967a4f06c5930f57220a3851c2b852210dfa207a9f76cc769650e31f03621d0362d7e5b3fea554672a7cc64

test:
  secret_key_base: 07cc8f1425678c3406c09ad2470cfe7d35bfbda9022c66bc556400398a08b1918fe31637794e463c8c19afc2ca1d1e804255bfbab3d12eeaf1c507b44dfd71ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
